Add script to calculate and plot times to collision (TTCs)
usdot-fhwa-stol/carma-analytics-fotda pull request #31
Opened 2024-03-13 21:02 UTC by adamlm

# PR Details
## Description

This PR adds a time to collision (TTC) calculation and plotting script.

## Related GitHub Issue

## Related Jira Key

[CDAR-730](https://usdot-carma.atlassian.net/browse/CDAR-730)

## Motivation and Context

Verification test metric

## How Has This Been Tested?

Manually with simulation data

## Types of changes

- [x] New feature (non-breaking change that adds functionality)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.

2024-03-14 13:01 UTC, paulbourelly999 commented on vru_use_case_scripts/plot_time_to_collision
> +COLLISION_THRESHOLD = 5.0
Add units to comment.

2024-03-14 13:02 UTC, paulbourelly999 commented on vru_use_case_scripts/plot_time_to_collision
> +    accumulated_time_ms = 0.0
Some of these local variable may benefit from some inline comments.

2024-03-14 13:03 UTC, paulbourelly999 commented on vru_use_case_scripts/plot_time_to_collision
> +    # Path(
Is this an oversight?

2024-03-14 13:03 UTC, paulbourelly999 commented on vru_use_case_scripts/plot_time_to_collision
> +    # Path(
Is this an over sight?

2024-03-14 13:04 UTC, paulbourelly999 commented on vru_use_case_scripts/plot_time_to_collision
> +plt.show()
What is you logic for displaying these plots instead of saving them?

2024-03-14 13:05 UTC, paulbourelly999 commented on vru_use_case_scripts/README.md
> +For each vehicle odometry point, the script propagates the vehicle forward along the path while keeping
May want to include an assumptions we make about vehicle (point mass or radius) and about stopped vehicles and pedestrians.

2024-03-14 14:57 UTC, MishkaMN requested changes

2024-03-14 14:57 UTC, MishkaMN commented on vru_use_case_scripts/plot_time_to_collision
> +COLLISION_THRESHOLD_M = 5.0
I don't think the parameter data is recorded in any of the topics. But the length of vehicle is 5 meters
https://github.com/usdot-fhwa-stol/carma-config/blob/develop/ail_vru_uc1_scenario/VehicleConfigParams.yaml#L22
Then the radius should be 5 / 2 + 1.2 (travel dist for pedestrian for 1s taken as its diameter) / 2 = 3.1

2024-03-14 20:20 UTC, paulbourelly999 approved these changes
Looks good to me

2024-03-18 15:49 UTC, MishkaMN approved these changes

2024-03-18 15:54 UTC, merged