Cf 871 Blue Truck B
usdot-fhwa-stol/carma-analytics-fotda pull request #75
Opened 2024-07-03 16:53 UTC by john-chrosniak

# PR Details
## Description

This PR includes a new script that compares the red and blue truck route tracking performance at varying speeds. Additionally, a bug fix for plotting the route driven is included.

## Related Jira Key

[CF-871](https://usdot-carma.atlassian.net/browse/CF-871)

## Motivation and Context

The Blue Truck had previously been locked into first gear using zipties. This was causing drive issues, so they were removed. After being removed the truck defaults to 2nd gear which has improved driving smoothness but localization quality has been negatively affected. It is likely that the VESC drive parameters need to be updated and a new parameter file will need to be created to delineate the two C1T trucks.

## How Has This Been Tested?

Data was collected from both trucks and plotted using the tool

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-07-03 16:53 UTC, john-chrosniak commented
![box_plots](https://github.com/usdot-fhwa-stol/carma-analytics-fotda/assets/43456793/ca585f58-0b90-40c0-851b-ec20311fc586)

2024-07-03 17:16 UTC, willjohnsonk requested changes

2024-07-03 17:16 UTC, willjohnsonk commented on src/carma-1-tenth/plot_multiple_crosstrack_errors.py
> +# Plot the crosstrack error as a function of downtrack (distance traveled along the route)
I'd just add some additional clarification that this is a box and whisker plot showing the crosstrack distribution or something along those lines that explains what the output looks like without generating the graph

2024-07-03 17:16 UTC, willjohnsonk commented on src/carma-1-tenth/plot_multiple_crosstrack_errors.py
> +def plot_multiple_crosstrack_errors(red_point_five_bag, red_point_seven_bag, red_one_bag, blue_point_five_bag, blue_point_seven_bag, blue_one_bag, show_plots=True):
Is there any easy way you could take an arbitrary number of input bags and add plots for each? That may require some annoying logic so I would alternative suggest a function that generates a single plot from a given bag so we aren't forced to use a specific number of inputs.

2024-07-08 13:56 UTC, willjohnsonk approved these changes

2024-07-08 14:34 UTC, merged