Purge C1T references
usdot-fhwa-stol/carma-analytics-fotda pull request #93
Opened 2024-10-28 20:37 UTC by john-chrosniak

# PR Details
## Description

This PR replaces references to CARMA1tenth (C1T) with CDA1tenth.

## Related GitHub Issue

NA

## Related Jira Key

[CF-947](https://usdot-carma.atlassian.net/browse/CF-947)

## Motivation and Context

CDA1tenth has been chosen as the name to encapsulate the Port Drayage proof-of-concept project and the follow-on workforce development project. So, we are replacing all references to the former CARMA1tenth (C1T) project to CDA1tenth.

## How Has This Been Tested?

All scripts run as expected with renaming.

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-05 16:12 UTC, john-chrosniak commented
No functional code was changed as part of this PR. The only change made were naming conventions, including the name of the directory from carma-1-tenth to cda-1-tenth (hence why the diff is highlighting all files).

2024-11-06 17:58 UTC, willjohnsonk requested changes

2024-11-06 17:58 UTC, willjohnsonk commented on src/cda-1-tenth/plot_steering_rate.py
> +# from ackermann_to_vesc_node parameters in cda1tenth_bringup/params/params.yaml
think this should be a hyphen

2024-11-06 19:20 UTC, willjohnsonk approved these changes
tested on vehicle

2024-11-06 20:19 UTC, merged