Arc 54 pt7 freq plot
usdot-fhwa-stol/carma-analytics-fotda pull request #99
Opened 2024-11-12 05:21 UTC by MishkaMN

# PR Details
## Description

This PR adds script to analyze a fixed rate publisher frequency over time from ROS2 tracing for nodes (interested ones are arbitrator, plan_delegator, trajectory_executor, pure_pursuit, and trajectory_follower_wrapper, but it does for everything as long as it says timer)

Convert selected nodes’ mean latency callback into frequency. 

Also convert the duration over time into frequency plot.

Design document for this task is here: https://leidoscorpus.sharepoint.us/:w:/r/sites/STR/TODevelopmentLibrary/22-256%20CDA%20Design%20%26%20Architecture/Work-In-Progress/Task%207%20Architecture%20Improvement%20Implementation/CARMA%20Platform%20Controls%20Improvements/Identified%20Core%20Performance%20Metrics%20And%20Analysis%20Design%20for%20CARMA%20Platform%20Control.docx?d=w40615c2fbfb74d439215cf62c5e5c4ca&csf=1&web=1&e=NXYkMT 
This implemented 8. and 9. from the design

## Related GitHub Issue
NA

## Related Jira Key
https://usdot-carma.atlassian.net/browse/ARC-54

## Motivation and Context
Control improvements under CDA DnA needed control performance analysis scripts.

## How Has This Been Tested?
To get the callback duration data from ros2_trace for each nodes run:
`python3 carma_analyze_callback_durations.py /workspaces/carma/carma_ws_ros2/src/analysis-data`

Example output:
![image](https://github.com/user-attachments/assets/1b913e0c-c7c4-4670-9e01-bf4a88155dc3)

"""
Callback,Mean Freq (Hz),Std Dev Freq,Min Freq (Hz),Max Freq (Hz)
lci_strategic_plugin Timer Callback period: 500 ms,1.9946396526341914,0.1178082570454688,0.3846936549782627,2.496797856748741
lci_strategic_plugin Timer Callback period: 100 ms,10.32943098817453,10.853643085545098,0.41715299753629437,359.8416696653072

"""

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [X] I have added any new packages to the sonar-scanner.properties file
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-11-12 16:07 UTC, john-chrosniak reviewed
Same comment as in #98, would be nice to have a README detailing the use of this script with plots shown.

2024-11-12 20:19 UTC, saina-ramyar commented
Generally looks good. Only comment is that the title of the plots are confusing, maybe is better to rephrase, or add a hyphen or comma so its not misleading.

2024-11-12 20:20 UTC, saina-ramyar requested changes
Generally looks good. Only comment is that the title of the plots are confusing, maybe is better to rephrase, or add a hyphen or comma so its not misleading.

2024-11-13 15:48 UTC, saina-ramyar approved these changes, later dismissed

2024-11-13 19:39 UTC, john-chrosniak submitted a review, later dismissed

2024-11-13 21:26 UTC, john-chrosniak approved these changes

2024-11-13 21:27 UTC, merged